name: CD-Deploy
on:
    push:
        branches:
            - 'main'
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'ap-southeast-7'
    MLFLOW_TRACKING_DNS: ${{ secrets.MLFLOW_TRACKING_DNS }}

jobs:
 build-push-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repo
       uses: actions/checkout@v2

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}

     - uses: hashicorp/setup-terraform@v2
       with:
         terraform_wrapper: false
     - name: Terraform plan
       id: tf-plan
       working-directory: 'inference/infrastructure/'
       run: |
         terraform init && terraform plan -var-file=prod.tfvars

     - name: Terraform apply (Step1 ECR)
       id: tf-apply-1
       working-directory: 'inference/infrastructure/'
       if: ${{ steps.tf-plan.outcome }} == 'success'
       run: |
         terraform apply -auto-approve -var-file=prod.tfvars -var "step=1"

     - name: Capture Terraform Outputs
       run: |
              ECR_REPO_URL=$(terraform output -raw ecr_repository_url 2>/dev/null || echo "")
              echo "ECR_REPO_URL=$ECR_REPO_URL" >> $GITHUB_ENV

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build Docker image and push to ECR
       id: build-push
       env:
         ECR_REPOSITORY_URL: ${{ env.ECR_REPO_URL }}
         IMAGE_TAG: "latest"
       run: |
         docker build -t "${{ env.ECR_REPOSITORY_URL }}:${{ env.IMAGE_TAG }}" .
         docker push "${{ env.ECR_REPOSITORY_URL }}:${{ env.IMAGE_TAG }}"

     - name: Terraform apply (Step2 Lambda)
       id: tf-apply-2
       working-directory: 'inference/infrastructure/'
       run: |
         terraform apply -auto-approve -var-file=prod.tfvars -var "step=2"
