name: CI-test
on:
  pull_request:
    branches:
      - 'main'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'ap-southeast-7'
  MLFLOW_TRACKING_DNS: ${{ secrets.MLFLOW_TRACKING_DNS }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install pipenv && pipenv install --dev

      - name: Execute Unit Testing
        working-directory: 'inference/tests/unit_test/'
        run: pipenv run pytest test_all.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Execute Integration Testing
      #   #working-directory: 'integration_testing/'
      #   run: |
      #     (cd integration_testing && sh run.sh)

  terrform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2
      - name: Terraform plan
        working-directory: 'inference/infrastructure/'
        run: |
          terraform init && terraform plan -var-file=prod.tfvars
